import { FaLocationDot } from "react-icons/fa6";
import { IoSearchOutline } from "react-icons/io5";
import { BiSolidImage } from "react-icons/bi";
import { AiFillWarning } from "react-icons/ai";
import { BsArrowRightCircleFill } from "react-icons/bs";
import { BsArrowLeftCircleFill } from "react-icons/bs";
import { AiFillSetting } from "react-icons/ai";
import { MdPolicy } from "react-icons/md";
import { BsHeadset } from "react-icons/bs";
import { MdManageAccounts } from "react-icons/md";
export { FaLocationDot, IoSearchOutline, BiSolidImage, AiFillWarning, BsArrowRightCircleFill, BsArrowLeftCircleFill, AiFillSetting, MdPolicy, BsHeadset, MdManageAccounts };
